// <auto-generated />
namespace Team9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Team94 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Team94));
        
        string IMigrationMetadata.Id
        {
            get { return "201612021235261_Team9.4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
